#!/bin/bash

IMAGE=action-notify

GIT_COMMITTER_USERNAME="user"
GIT_COMMITTER_MESSAGE_ESCAPED="a message"
GITHUB_JOB_STATUS=success
DISCORD_WEBHOOK_URL=$(jq -r .DISCORD_WEBHOOK_URL ./.config/secret.json)

docker build -t $IMAGE .

docker run --rm \
	-e GIT_COMMITTER_USERNAME="${GIT_COMMITTER_USERNAME}" \
	-e GIT_COMMIT_MESSAGE_ESCAPED="${GIT_COMMITTER_MESSAGE_ESCAPED}" \
	-e GITHUB_JOB_STATUS="${GITHUB_JOB_STATUS}" \
	-e DISCORD_WEBHOOK_URL="${DISCORD_WEBHOOK_URL}" \
	$IMAGE
